/**
 * import-csv.mjs
 * data/actors.csv + data/categories.csv → src/data.js
 *
 * Run manually when the CSV files are the source of edits:
 *   node scripts/import-csv.mjs
 *
 * After running, the next `npm run dev` / `npm run build` will pick up
 * the updated data.js and re-export fresh CSVs to confirm round-trip parity.
 */

import { readFileSync, writeFileSync } from 'fs';
import { fileURLToPath } from 'url';
import { dirname, join } from 'path';

const root = dirname(dirname(fileURLToPath(import.meta.url)));

/* ── CSV parser (handles quoted fields with embedded commas/newlines) ─────── */
function parseCSV(text) {
  const lines = text.trim().split('\n');
  const headers = parseRow(lines[0]);
  return lines.slice(1)
    .filter(l => l.trim())
    .map(line => {
      const vals = parseRow(line);
      return Object.fromEntries(headers.map((h, i) => [h, (vals[i] ?? '').trim()]));
    });
}

function parseRow(line) {
  const cells = [];
  let i = 0, cur = '';
  while (i < line.length) {
    if (line[i] === '"') {
      i++;
      while (i < line.length) {
        if (line[i] === '"' && line[i + 1] === '"') { cur += '"'; i += 2; }
        else if (line[i] === '"') { i++; break; }
        else { cur += line[i++]; }
      }
    } else if (line[i] === ',') {
      cells.push(cur); cur = ''; i++;
    } else {
      cur += line[i++];
    }
  }
  cells.push(cur);
  return cells;
}

/* ── Read CSVs ────────────────────────────────────────────────────────────── */
const actors  = parseCSV(readFileSync(join(root, 'data/actors.csv'),     'utf8'));
const cats    = parseCSV(readFileSync(join(root, 'data/categories.csv'), 'utf8'));

/* ── Build data.js ────────────────────────────────────────────────────────── */
function j(v) { return JSON.stringify(v); }

const catsBlock = `export const CATS = {\n` +
  cats.map(c =>
    `  ${j(c.name)}: { dot: ${j(c.color)}, desc: ${j(c.description)} }`
  ).join(',\n') +
  '\n};\n';

const actorsBlock = `export const ACTORS = [\n` +
  actors.map(a => {
    const obj = {
      n: a.name,
      c: a.category,
      r: a.role,
      t: a.tags ? a.tags.split('|').map(s => s.trim()).filter(Boolean) : [],
      ...(a.link ? { link: a.link } : {}),
    };
    return '  ' + JSON.stringify(obj);
  }).join(',\n') +
  '\n];\n';

const output = [
  '// AUTO-GENERATED by scripts/import-csv.mjs',
  '// Edit the data/ CSV files, then run:  npm run import-csv',
  '// To export the current JS back to CSV: npm run export-csv',
  '',
  catsBlock,
  actorsBlock,
].join('\n');

writeFileSync(join(root, 'src/data.js'), output);
console.log('✓  src/data.js regenerated from data/ CSV files');
